name:                GBOL
version:             0.1.0.0
github:              "ianmelendez95/GBOL"
license:             BSD3
author:              "Ian Melendez"
maintainer:          "ian.melendez.95@gmail.com"
copyright:           "2022 Ian Melendez"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ianmelendez95/GBOL#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - text
  - megaparsec
  - containers
  - generic-deriving
  - split
  - lens
  - bytestring
  - file-embed
  - mtl
  - bimap

executables:
  gbol:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GBOL

tests:
  gbol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GBOL
